// Build the frontend and headless bridge first. Set KLAUS_PLAYWRIGHT to a local
// Playwright module when it is not installed in this workspace. Uses scratch data.
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { mkdtemp, readFile, rm, mkdir, cp, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { build } from 'esbuild';
import { PDFDocument, StandardFonts, degrees } from 'pdf-lib';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const playwright = require(process.env.KLAUS_PLAYWRIGHT || 'playwright');
const browserName = process.env.KLAUS_TEST_BROWSER || 'chromium';
assert(['chromium', 'webkit'].includes(browserName));
const scratch = await mkdtemp(join(tmpdir(), 'klaus-library-test-'));
const capture = process.env.KLAUS_LIBRARY_CAPTURES || join(scratch, 'captures');
await mkdir(capture, { recursive: true });
await cp(join(root, 'build'), join(root, 'target/debug/web'), { recursive: true });
await build({ stdin: { contents: `export * from './vendor/anki/out/ts/lib/generated/anki/generic_pb'; export * from './vendor/anki/out/ts/lib/generated/anki/notes_pb'; export * from './vendor/anki/out/ts/lib/generated/anki/search_pb'; export * from './vendor/anki/out/ts/lib/generated/anki/cards_pb'; export * from './vendor/anki/out/ts/lib/generated/anki/notetypes_pb'; export * from './vendor/anki/out/ts/lib/generated/anki/scheduler_pb'; export * from './vendor/anki/out/ts/lib/generated/klaus_pb';`, resolveDir: root }, bundle: true, platform: 'node', format: 'cjs', outfile: join(scratch, 'proto.cjs') });
const { Json, SearchRequest, SearchResponse, NoteId, Note, NotetypeId, AddNoteRequest, AddNoteResponse, Card, CardId, QueuedCards, GetQueuedCardsRequest, RenderCardRequest } = require(join(scratch, 'proto.cjs'));
const pdf = await PDFDocument.create(), font = await pdf.embedFont(StandardFonts.Helvetica);
for (const text of ['Library specimen page one', 'Acetylcholine example page two']) {
  const sheet = pdf.addPage([595, 842]);
  sheet.drawText(text, { x: 48, y: 760, size: 18, font });
}
const bytes = Buffer.from(await pdf.save());
const server = spawn(join(root, 'target/debug/examples/headless'), [scratch], { cwd: root });
let browser;
try {
  const auth = await new Promise((resolveURL, reject) => {
    let output = '';
    const timeout = setTimeout(() => reject(new Error('Headless bridge did not start')), 15000);
    server.once('exit', code => { clearTimeout(timeout); reject(new Error(`Bridge exited ${code}`)); });
    server.stdout.on('data', chunk => {
      output += chunk;
      const match = output.match(/KlausNote dev URL: (\S+)/);
      if (match) { clearTimeout(timeout); resolveURL(match[1]); }
    });
  });
  const base = new URL(auth).origin;
  browser = await playwright[browserName].launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 }, reducedMotion: 'reduce' });
  const screenshot = options => process.env.KLAUS_LIBRARY_SKIP_CAPTURES ? Promise.resolve() : page.screenshot(options);
  page.setDefaultTimeout(15000);
  page.on('dialog', dialog => dialog.accept());
  const errors = [];
  page.on('pageerror', error => errors.push(error.stack || String(error)));
  let reads = 0;
  page.on('request', request => { if (request.url().endsWith('/_anki/klausLibraryRead')) reads++; });
  await page.goto(auth);
  await page.getByRole('button', { name: 'Library', exact: true }).click();
  await page.getByRole('heading', { name: 'Library', exact: true }).waitFor();
  assert.equal(await page.locator('header').getByRole('button', { name: 'Toggle card editor', exact: true }).count(), 1, 'Pane controls belong in the main top bar');
  await page.getByText('Your PDFs belong here').waitFor();
  const frame = page.frameLocator('#library-editor');
  const fields = frame.locator('anki-editable[contenteditable="true"]');
  await fields.first().waitFor();
  await screenshot({ path: join(capture, 'empty-desktop.png'), fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Create folder', exact: true }).click();
  await page.getByLabel('Folder name', { exact: true }).fill('Physiology');
  await page.getByRole('button', { name: 'Create folder', exact: true }).last().click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.getByRole('button', { name: 'Physiology', exact: true }).click();
  await page.getByLabel('Import PDFs', { exact: true }).setInputFiles({ name: 'Study.pdf', mimeType: 'application/pdf', buffer: bytes });
  await page.locator('canvas[aria-label="PDF page 1"]').waitFor();
  await page.locator('.textLayer').getByText('Library specimen page one', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Next page', exact: true }).click();
  await page.locator('.textLayer').getByText('Acetylcholine example page two', { exact: true }).waitFor();
  await page.getByLabel('Find in PDF', { exact: true }).fill('specimen');
  await page.getByRole('button', { name: 'Find next matching page', exact: true }).click();
  await page.getByText('Found on page 1', { exact: true }).waitFor();
  assert.equal(reads, 1, 'Paging and search must not reopen the PDF');
  const unusual = await PDFDocument.create();
  unusual.addPage([500, 100000]);
  unusual.addPage([595, 842]).setRotation(degrees(90));
  await page.getByLabel('Import PDFs', { exact: true }).setInputFiles({ name: 'Unusual.pdf', mimeType: 'application/pdf', buffer: Buffer.from(await unusual.save()) });
  await page.getByRole('heading', { name: 'Unusual.pdf', exact: true }).waitFor();
  await page.locator('canvas[aria-label="PDF page 1"]').waitFor();
  await assertEventually(() => page.locator('.library-pdf-page canvas').evaluate(canvas => String(canvas.height)), value => Number(value) > 1);
  const dimensions = await page.locator('.library-pdf-page canvas').evaluate(canvas => [canvas.width, canvas.height]);
  assert(dimensions[0] <= 4096 && dimensions[1] <= 4096 && dimensions[0] * dimensions[1] <= 8 * 1024 * 1024, 'Extreme PDF raster exceeds budget');
  await page.getByRole('button', { name: 'Next page', exact: true }).click();
  await page.locator('canvas[aria-label="PDF page 2"]').waitFor();
  await page.getByRole('button', { name: 'Study.pdf', exact: true }).click();
  await page.locator('.textLayer').getByText('Library specimen page one', { exact: true }).waitFor();
  await fields.nth(1).click();
  await fields.nth(1).pressSequentially('Answer retained while reading');
  await page.getByRole('button', { name: 'Toggle card editor', exact: true }).click();
  await page.evaluate(() => new Promise(resolveFrame => requestAnimationFrame(() => requestAnimationFrame(resolveFrame))));
  await page.locator('.textLayer').getByText('Library specimen page one', { exact: true }).waitFor();
  await page.locator('.textLayer').evaluate(layer => {
    const range = document.createRange(); range.selectNodeContents(layer);
    const selection = getSelection(); selection.removeAllRanges(); selection.addRange(range);
    document.dispatchEvent(new Event('selectionchange'));
  });
  await page.getByRole('button', { name: 'Insert selected text into card', exact: true }).click();
  try {
    await assertEventually(() => fields.nth(1).textContent(), value => value.includes('Library specimen page one') && value.includes('Answer retained while reading'));
  } catch (error) {
    throw new Error(`${error.message}. Fields: ${JSON.stringify(await fields.allTextContents())}`);
  }
  await page.getByRole('button', { name: 'Toggle files pane', exact: true }).click();
  await page.getByRole('button', { name: 'Toggle files pane', exact: true }).click();
  // A headless bridge has no native dialogs. Supply the user's decision while
  // exercising the real Anki close check and Library navigation guard.
  await page.evaluate(() => { window.confirm = () => false; });
  await page.getByRole('link', { name: 'Decks', exact: true }).click();
  assert.equal(new URL(page.url()).pathname, '/library');
  assert((await fields.nth(1).textContent()).includes('Answer retained'));
  await fields.first().click();
  await fields.first().pressSequentially('Library integration question');
  const added = page.waitForResponse(response => response.url().endsWith('/_anki/addNote') && response.request().method() === 'POST');
  await frame.getByRole('button', { name: 'Add', exact: true }).click();
  const addition = await added;
  assert(addition.ok(), 'Anki Add failed');
  const search = await page.request.post(base + '/_anki/searchNotes', { headers: { 'Content-Type': 'application/binary' }, data: Buffer.from(new SearchRequest({ search: '"Library integration question"' }).toBinary()) });
  assert(search.ok(), 'Saved Note search failed');
  const ids = SearchResponse.fromBinary(await search.body()).ids;
  assert.equal(ids.length, 1, 'Anki Add must persist exactly one matching Note');
  const noteId = ids[0];
  const stored = await page.request.post(base + '/_anki/getNote', { headers: { 'Content-Type': 'application/binary' }, data: Buffer.from(new NoteId({ nid: noteId }).toBinary()) });
  assert(stored.ok(), `Saved Note ${noteId} unavailable: HTTP ${stored.status()} ${await stored.text()}`);
  const saved = Note.fromBinary(await stored.body());
  assert.equal(saved.fields[0], 'Library integration question');
  assert(saved.fields[1].includes('Answer retained while reading') && saved.fields[1].includes('Library specimen page one'));
  await assertEventually(() => fields.first().textContent(), value => !value.includes('Library integration question'));
  await page.locator('[data-sonner-toast]').first().waitFor({ state: 'hidden' });
  await screenshot({ path: join(capture, 'desktop.png'), fullPage: true, animations: 'disabled' });
  await page.emulateMedia({ colorScheme: 'dark' });
  await page.reload();
  await page.locator('.textLayer').getByText('Library specimen page one', { exact: true }).waitFor();
  await fields.first().waitFor();
  await screenshot({ path: join(capture, 'desktop-dark.png'), fullPage: true, animations: 'disabled' });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('radio', { name: 'Reader', exact: true }).click();
  assert.equal(await page.locator('header').getByRole('radio', { name: 'Card editor', exact: true }).count(), 1, 'Narrow pane controls belong in the main top bar');
  await page.locator('.library-pdf-page canvas').waitFor();
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile overflow');
  await screenshot({ path: join(capture, 'mobile.png'), fullPage: true, animations: 'disabled' });
  await page.getByRole('radio', { name: 'Card editor', exact: true }).click();
  await fields.first().click();
  await fields.first().pressSequentially('Mobile draft');
  await page.getByRole('radio', { name: 'Reader', exact: true }).click();
  await page.getByRole('radio', { name: 'Card editor', exact: true }).click();
  assert.equal(await fields.first().textContent(), 'Mobile draft');
  await screenshot({ path: join(capture, 'mobile-card.png'), fullPage: true, animations: 'disabled' });
  await page.evaluate(() => { window.confirm = () => true; });
  await page.getByRole('button', { name: 'Navigation', exact: true }).click();
  await page.getByRole('menuitem', { name: 'Decks', exact: true }).click();
  await page.waitForURL(base + '/', { waitUntil: 'domcontentloaded' });
  await page.waitForLoadState('networkidle');
  const rpc = async (method, input, output) => {
    const response = await page.request.post(base + '/_anki/' + method, { headers: { 'Content-Type': 'application/binary' }, data: Buffer.from(input.toBinary()) });
    assert(response.ok(), `${method} failed: HTTP ${response.status()}`);
    return output.fromBinary(await response.body());
  };
  const persisted = nid => rpc('getNote', new NoteId({ nid }), Note);
  const fieldText = html => page.evaluate(value => { const node = document.createElement('div'); node.innerHTML = value; return node.textContent; }, html);
  const sibling = await rpc('newNote', new NotetypeId({ ntid: saved.notetypeId }), Note);
  sibling.fields = ['Browser sibling question', 'Browser sibling answer'];
  const siblingAdded = await rpc('addNote', new AddNoteRequest({ note: sibling, deckId: 1n }), AddNoteResponse);
  const siblingId = siblingAdded.noteId;
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.emulateMedia({ colorScheme: 'light' });
  await page.goto(base + '/browse');
  const rows = page.getByRole('grid', { name: 'Search results', exact: true });
  const row = text => rows.locator('tr[aria-rowindex]').filter({ hasText: text });
  const browserEditor = page.frameLocator('iframe[title="Editor"]');
  const browserFields = browserEditor.locator('anki-editable[contenteditable="true"]');
  await row('Library integration question').click();
  await assertEventually(() => browserFields.first().textContent(), value => value.includes('Library integration question'));
  await browserFields.first().click();
  await browserFields.first().press('End');
  await browserFields.first().pressSequentially(' Browser saved edit');
  await row('Browser sibling question').click();
  await assertEventually(() => browserFields.first().textContent(), value => value.includes('Browser sibling question'));
  assert((await persisted(noteId)).fields[0].includes('Browser saved edit'), 'Browser must save before switching Notes');
  await browserFields.first().click();
  await browserFields.first().press('End');
  await browserFields.first().pressSequentially(' Browser field and tag edit');
  await browserEditor.locator('.tag-editor .tag-spacer').click();
  await browserEditor.locator('input.tag-input').pressSequentially('browser-tag');
  await page.getByRole('link', { name: 'Decks', exact: true }).click();
  await page.waitForURL(base + '/', { waitUntil: 'domcontentloaded' });
  await page.waitForLoadState('networkidle');
  const siblingSaved = await persisted(siblingId);
  assert(siblingSaved.fields[0].includes('Browser field and tag edit'), 'Browser must save fields before leaving');
  assert(siblingSaved.tags.includes('browser-tag'), 'Browser must drain pending tag saves before leaving');
  await page.goto(base + '/browse');
  await row('Browser sibling question').click();
  await assertEventually(() => browserFields.first().textContent(), value => value.includes('Browser sibling question'));
  await assertEventually(() => page.locator('iframe[title="Editor"]').evaluate(frame => frame.inert ? 'busy' : 'ready'), value => value === 'ready');
  const failedWrite = route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: 'Forced scratch save failure' }) });
  await page.route('**/_anki/updateNotes', failedWrite);
  const browserFailure = page.waitForResponse(response => response.url().endsWith('/_anki/updateNotes') && response.status() === 500);
  await browserFields.first().click();
  await browserFields.first().press('End');
  await browserFields.first().pressSequentially(' Blocked Browser draft');
  await browserFailure;
  const dismissFailure = async title => {
    const dialog = page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: title, exact: true }) });
    await dialog.waitFor();
    assert((await browserFields.first().textContent()).includes('Blocked Browser draft'), 'Failed save must keep typed Browser draft');
    await dialog.getByRole('button', { name: 'Close', exact: true }).last().click();
    await dialog.waitFor({ state: 'hidden' });
  };
  for (let attempt = 0; attempt < 2; attempt++) {
    await row('Library').click();
    await dismissFailure('Could not change the selected note');
  }
  await page.getByRole('link', { name: 'Decks', exact: true }).click();
  await dismissFailure('Could not save the editor');
  assert.equal(new URL(page.url()).pathname, '/browse', 'Failed save must block Browser navigation');
  assert(!(await persisted(siblingId)).fields[0].includes('Blocked Browser draft'), 'Forced failure must not persist the draft');
  const modes = page.locator('[aria-label="Show cards or notes"] [data-slot="toggle-group-item"]');
  const modeState = () => modes.evaluateAll(items => items.map(item => [item.textContent, item.getAttribute('aria-checked'), item.getAttribute('aria-pressed'), item.getAttribute('data-state')]));
  const modeBefore = await modeState();
  await modes.filter({ hasText: /^Notes$/ }).click();
  await dismissFailure('Could not change the browser mode');
  assert.deepEqual(await modeState(), modeBefore, 'Failed save must block Cards/Notes mode changes');
  await page.getByRole('searchbox', { name: 'Search', exact: true }).fill('nid:0');
  await page.getByRole('searchbox', { name: 'Search', exact: true }).press('Enter');
  await dismissFailure('Could not change the selected note');
  assert(await browserFields.first().isVisible(), 'An empty search must not hide a failed draft');
  await page.getByRole('searchbox', { name: 'Search', exact: true }).fill('deck:current');
  await page.getByRole('searchbox', { name: 'Search', exact: true }).press('Enter');
  await row('Library').waitFor();
  const browserDraft = await browserFields.first().textContent();
  await page.unroute('**/_anki/updateNotes', failedWrite);
  await browserFields.first().click();
  await browserFields.first().press('End');
  await browserFields.first().pressSequentially(' Browser recovery');
  const browserRecoveredDraft = await browserFields.first().textContent();
  await row('Library').click();
  await assertEventually(() => browserFields.first().textContent(), value => value.includes('Library') && value.includes('Browser saved edit'));
  const recovered = await persisted(siblingId);
  const recoveredText = await fieldText(recovered.fields[0]);
  assert.equal(recoveredText, browserRecoveredDraft, 'Acknowledged edit must persist the typed draft exactly');
  assert.equal(recoveredText.replace(' Browser recovery', ''), browserDraft, 'Recovery must retain previous typed content');
  await modes.filter({ hasText: /^Notes$/ }).click();
  await assertEventually(() => modes.filter({ hasText: /^Notes$/ }).getAttribute('aria-checked'), value => value === 'true');
  await assertEventually(() => page.locator('iframe[title="Editor"]').evaluate(frame => frame.inert ? 'busy' : 'ready'), value => value === 'ready');
  assert((await browserFields.first().textContent()).includes('Browser saved edit'), 'Successful mode change must keep the displayed Note');
  await modes.filter({ hasText: /^Cards$/ }).click();
  await assertEventually(() => modes.filter({ hasText: /^Cards$/ }).getAttribute('aria-checked'), value => value === 'true');
  await assertEventually(() => page.locator('iframe[title="Editor"]').evaluate(frame => frame.inert ? 'busy' : 'ready'), value => value === 'ready');
  await page.getByRole('link', { name: 'Decks', exact: true }).click();
  await page.waitForURL(base + '/', { waitUntil: 'domcontentloaded' });
  await page.waitForLoadState('networkidle');
  const queued = () => rpc('getQueuedCards', new GetQueuedCardsRequest({ fetchLimit: 2, intradayLearningOnly: false }), QueuedCards);
  const queueBefore = await queued();
  const renderIds = [];
  let answers = 0;
  page.on('request', request => {
    if (request.url().endsWith('/_anki/klausRenderCard')) renderIds.push(RenderCardRequest.fromBinary(request.postDataBuffer()).cardId);
    if (request.url().endsWith('/_anki/answerCard')) answers++;
  });
  await page.goto(base + '/review?deck=1');
  await page.getByRole('button', { name: 'Show Answer', exact: true }).waitFor();
  await assertEventually(() => page.getByRole('button', { name: 'Show Answer', exact: true }).isEnabled().then(enabled => enabled ? 'ready' : 'busy'), value => value === 'ready');
  const currentCardId = renderIds.at(-1);
  assert(currentCardId, 'Study must render a current Card');
  const cardBefore = await rpc('getCard', new CardId({ cid: currentCardId }), Card);
  await page.getByRole('button', { name: 'Show Answer', exact: true }).click();
  await page.getByRole('button', { name: /Easy/ }).waitFor();
  const currentCard = page.frameLocator('iframe[title="Card"]').locator('#qa');
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  const studyDialog = page.getByRole('dialog').filter({ has: page.getByRole('heading', { name: 'Edit current note', exact: true }) });
  const studyEditor = page.frameLocator('iframe[title="Edit current note"]');
  const studyFields = studyEditor.locator('anki-editable[contenteditable="true"]');
  await studyFields.nth(1).waitFor();
  await studyFields.nth(1).click();
  await studyFields.nth(1).press('End');
  await studyFields.nth(1).pressSequentially(' Study saved answer');
  await studyDialog.getByRole('button', { name: 'Done', exact: true }).click();
  await studyDialog.waitFor({ state: 'hidden' });
  await assertEventually(() => currentCard.textContent(), value => value.includes('Study saved answer'));
  assert.equal(renderIds.at(-1), currentCardId, 'Study save must render the same Card');
  assert.equal(await page.getByRole('button', { name: 'Show Answer', exact: true }).count(), 0, 'Study save must preserve the answer side');
  assert((await persisted(cardBefore.noteId)).fields[1].includes('Study saved answer'));
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await studyFields.nth(1).waitFor();
  await assertEventually(() => studyDialog.getByRole('button', { name: 'Done', exact: true }).isEnabled().then(enabled => enabled ? 'ready' : 'busy'), value => value === 'ready');
  await page.route('**/_anki/updateNotes', failedWrite);
  const studyFailure = page.waitForResponse(response => response.url().endsWith('/_anki/updateNotes') && response.status() === 500);
  await studyFields.nth(1).click();
  await studyFields.nth(1).press('End');
  await studyFields.nth(1).pressSequentially(' Blocked Study draft');
  await studyFailure;
  for (let attempt = 0; attempt < 2; attempt++) {
    await studyDialog.getByRole('button', { name: 'Done', exact: true }).click();
    await studyDialog.getByRole('alert').waitFor();
    assert((await studyFields.nth(1).textContent()).includes('Blocked Study draft'), 'Failed Done must keep the Study draft');
    assert.equal(renderIds.at(-1), currentCardId);
  }
  assert(!(await persisted(cardBefore.noteId)).fields[1].includes('Blocked Study draft'));
  const studyDraft = await studyFields.nth(1).textContent();
  await page.unroute('**/_anki/updateNotes', failedWrite);
  await studyFields.nth(1).click();
  await studyFields.nth(1).press('End');
  await studyFields.nth(1).pressSequentially(' Study recovery');
  const studyRecoveredDraft = await studyFields.nth(1).textContent();
  await studyDialog.getByRole('button', { name: 'Done', exact: true }).click();
  await studyDialog.waitFor({ state: 'hidden' });
  await assertEventually(() => currentCard.textContent(), value => value.includes('Study recovery'));
  const studyRecovered = await persisted(cardBefore.noteId);
  const studyRecoveredText = await fieldText(studyRecovered.fields[1]);
  assert.equal(studyRecoveredText, studyRecoveredDraft, 'Study recovery must persist the exact typed draft');
  assert.equal(studyRecoveredText.replace(' Study recovery', ''), studyDraft, 'Study recovery must retain previous typed content');
  const cardAfter = await rpc('getCard', new CardId({ cid: currentCardId }), Card);
  for (const key of ['id', 'noteId', 'deckId', 'ctype', 'queue', 'due', 'interval', 'reps', 'lapses']) assert.equal(cardAfter[key], cardBefore[key], `Study editing changed Card ${key}`);
  const queueAfter = await queued();
  assert.deepEqual(queueAfter.cards.map(entry => entry.card.id), queueBefore.cards.map(entry => entry.card.id), 'Study editing must retain the queue');
  assert.deepEqual([queueAfter.newCount, queueAfter.learningCount, queueAfter.reviewCount], [queueBefore.newCount, queueBefore.learningCount, queueBefore.reviewCount]);
  assert.equal(answers, 0, 'Study editing must never call answerCard');
  assert(renderIds.every(id => id === currentCardId), 'Study editing must never switch Cards');
  assert.equal(await page.getByRole('button', { name: 'Show Answer', exact: true }).count(), 0);
  const listing = await page.request.post(base + '/_anki/klausLibraryList', { headers: { 'Content-Type': 'application/binary' }, data: Buffer.from(new Json({ json: new TextEncoder().encode('{"path":"Physiology"}') }).toBinary()) });
  assert(listing.ok());
  assert.deepEqual(await readFile(join(scratch, 'Library/Physiology/Study.pdf')), bytes);
  assert.deepEqual(errors, []);
  const result = JSON.stringify({ passed: true, browser: browserName, checks: ['folder and PDF import', 'selectable PDF', 'paging and search', 'hidden-editor text insertion', 'card creation', 'declined and accepted discard', 'pane draft retention', 'persisted document', 'desktop/dark/mobile layout', 'bounded canvas', 'Browser switch saves', 'Browser fields and tag saves before navigation', 'Browser failed save blocks repeated switch and navigation', 'Browser failed save blocks Cards/Notes mode change', 'Browser empty search retains failed draft', 'Browser retained draft recovery', 'Browser successful Cards/Notes mode changes', 'Study save preserves Card and answer side', 'Study failed Done preserves draft', 'Study acknowledged recovery', 'Study queue and scheduling unchanged without answering'], errors }, null, 2);
  await writeFile(join(capture, `result-${browserName}.json`), result);
  await writeFile(join(capture, 'result.json'), result);
  console.log(`PASS Library, Browser and Study in ${browserName} with real scratch bridge, persisted fields/tags, blocked failed saves, retained draft recovery, unchanged Study Card/answer/queue, and no answerCard`);
} finally {
  await browser?.close();
  server.kill('SIGTERM');
  await rm(scratch, { recursive: true, force: true });
}

async function assertEventually(read, predicate) {
  for (let i = 0; i < 40; i++) {
    if (predicate((await read()) || '')) return;
    await new Promise(resolveWait => setTimeout(resolveWait, 100));
  }
  assert.fail('Expected editor content did not arrive');
}
