#!/bin/sh
# Generates Anki's TypeScript library into vendor/anki/out/ts/lib/generated, the
# same place Anki's own build puts it (aliased as @generated by Klaus and Anki):
# backend.ts and ftl.ts from rslib's build scripts, Anki's hand-written helpers,
# and the *_pb.ts message types from protoc-gen-es (same version Anki pins).
set -e
cd "$(dirname "$0")/.."
cargo build -q -p anki_proto -p anki_i18n
out=vendor/anki/out/ts/lib/generated
cp vendor/anki/ts/lib/generated/*.ts "$out/"
# protoc.exe can't run npm's extensionless shim on Windows, and runs the .cmd
# through cmd.exe, which needs a native backslash path.
plugin=node_modules/.bin/protoc-gen-es
case "$(uname -s)" in MINGW*|MSYS*|CYGWIN*) plugin=$(cygpath -w "$PWD/$plugin.cmd") ;; esac
protoc --plugin=protoc-gen-es="$plugin" \
  --es_out="$out" --es_opt=target=ts \
  -I vendor/anki/proto vendor/anki/proto/anki/*.proto
# Klaus's own bridge messages, as @generated/klaus_pb.
protoc --plugin=protoc-gen-es="$plugin" \
  --es_out="$out" --es_opt=target=ts \
  -I crates/bridge/proto -I vendor/anki/proto crates/bridge/proto/klaus.proto
